### ISSUE TITLE
Output warning if Access row count exceeded.

### ISSUE THREAD

**Issue by benhudson85** [cat-cfs/cbm3_python#13]
https://github.com/cat-cfs/cbm3_python/blob/4308b74542a53fdbb4991153c6891d7f51c17491/cbm3_python/cbm3data/cbm3_results_db_writer.py#L49

Output a clear warning when the results database format is Access and the maximum row count for a given table is exceeded. This happens often for tblFluxIndicators when the simulation period is very long (probably also tblAgeIndicators). Database is still created with tables that were able to get through and a quick database size check does not make the issue apparent. Maybe write a text file beside the results database called "RESULTS_ERROR.txt" or something similar? Not sure if I've referenced the correct line of code.

**Comment by smorken** [comment]
We cannot directly detect this in cbm3_python since it occurs in an underlying toolbox (.net) process. 

Added some support methods to CBM3 python to detect this situation and raise an error.  By checking the row totals from the following 2 methods the error can be detected.  In both methods a `pandas.DataFrame` with a single row is returned.

I propose that we integrate this in [project_simulator](https://github.com/cat-cfs/cbm3_python/blob/master/cbm3_python/simulation/projectsimulator.py)

## 1. method to [count the number of rows](https://github.com/cat-cfs/cbm3_python/blob/c706e448d5eb752ce61083ab0709e3ce2613bdae/cbm3_python/cbm3data/cbm3_results.py#L32) in a loaded database

Example 

```python
from cbm3_python.cbm3data import cbm3_results
df = cbm3_results.load_row_counts("my_project/my_results_database.mdb")
```

## 2. method to [count the number of rows in output files](https://github.com/cat-cfs/cbm3_python/blob/c706e448d5eb752ce61083ab0709e3ce2613bdae/cbm3_python/cbm3data/cbm3_output_files.py#L742)

This was more complicated, since it is necessary to exclude rows that have duplicated key values form the total counts.

Example

```python
from cbm3_python.cbm3data import cbm3_output_files
df = cbm3_output_files.load_row_counts("my_project/tempfiles/CBMRun/output")
```

**Comment by benhudson85** [comment]
I think the proposed method #1, assessing row count in the output database, is a suitable solution. I assume this means there is some known maximum row count in an Access database that can be compared against?

**Comment by smorken** [comment]
closing, as the row count methods are implemented and being integrated into separate workflow
