### ISSUE TITLE
adding a user defined classifier for sit automation

### ISSUE THREAD

**Issue by BlaneG** [cat-cfs/cbm3_python#9]
I couldn't find any examples of how to add a new classifier in the [sit_automation examples](https://github.com/cat-cfs/cbm3_python/tree/master/examples/sit_automation).

 For example, if I wanted to generate a 'Scenario' classifier, I could update `sit_classifiers.csv`:
| id |      name |  description |
|----------|:-------------:|------:|
| 1 |  _CLASSIFIER | Eco |
| 1 |   mc |  Montane Cordillera |
| 2 | _CLASSIFIER  |    Scenario |
| 2 | scenario_a |    scenario a|

Updating `sit_classifiers.csv` for the `admin_eco_classifier` [example](https://github.com/cat-cfs/cbm3_python/tree/master/examples/sit_automation/admin_eco_classifier) and calling() `sit_helper.csv_import` raises an error message.  I guess the mapping.json file might need to be updated but it's not clear what needs to be added.  For example, I tried adding, the following to mapping.json, but had no luck:
```	
"scenario": {
	"scenario_classifier": "Scenario",
	"scenario_mapping": [
		{"user_scenario": "scenario_a", "default_scenario": "scenario a"}
	]
},
```

**Comment by smorken** [comment]
This would be the same process as adding a classifier in any CBM-CFS3 SIT dataset.  Note that the classifiers defined in the SIT_Classifier file form part of the column definitions in the inventory, yields, events, and transition rules.  This does mean that in order to add a new classifier you need to modify all of those files as well. 

The mapping definition in mapping.json will only come into play if your scenario classifier is mappable to CBM-CFS3 default parameters (species, spatial units, or non-forest cover types) This means you may not need to modify the mapping file at all when adding a new scenario classifier, unless the scenario classifier itself is mappable to species for example.

**Comment by BlaneG** [comment]
Thanks. It was helpful to know that `mapping.json` only needs to include mappings used for CBM-CFS3 default classifiers.
